### ISSUE TITLE
Make Dockerfile for Engine Service

### ISSUE THREAD

**Issue by amilworks** [UCSB-VRL/bisque-modules#1]
## Engine Service `Dockerfile`

Pending task is to make the `Dockerfile` for the engine service so we can add this repo to our CI/CD pipeline. We can use a modified version of the base image. For example, inherit from the main repo:

```docker
FROM bisqueUCSB-REPO

RUN git clone bisque-modules-REPO

```

Then send it off to update the backend engine service.

**Comment by connor11son** [comment]
This is will be solved in https://github.com/UCSB-VRL/bisqueUCSB
